### PR TITLE
Fix/adjust navigation bar and font size in layout

### PR DESCRIPTION
**Pull request by ljc1991**
# Description

- Adjust navigation bar 
- Adjust font-size in text

## minor

- remove page content navigation in activities page and cards page
- change font-size from 14px to 16px in text of section
- (inactive) add dynamic page navigation list

# Impaction

## Screenshots

| Scenarios  | Before | After |
| ---------- | ------ | ----- |
| NavBar | 截圖 2023-09-22 13 52 41 | 截圖 2023-09-22 13 52 49 |
| font-size | 截圖 2023-09-22 13 53 06 | 截圖 2023-09-22 13 53 20 |

### Build and deploy time

N/A

### LightHouse

N/A

### CODE REVIEW

**Comment by ben196888** [comment]
Please remove the unused CSS instead of comment them out.

**Comment by ben196888** [comment]
It's very good to have dynamic navigation links. 🥳 Nice work!

May I know your reason not to replace the hard code approach?

**Comment by ljc1991** [comment]
> It's very good to have dynamic navigation links. 🥳 Nice work!
> 
> May I know your reason not to replace the hard code approach?

I think it will be better to wait until the content for the resource page is completely updated. 
BTW, I haven't added the links to the cards page and activities page in the dynamic navigation list yet...

**Comment by ben196888** [comment]
There are some duplicate lines of code on generating the navigation list. Please create a shared function and reuse it.

**Comment by ben196888** [comment]
Good work!!!

**Review by ben196888 — APPROVED** [review]

**Pull request merged**
